<?php
/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Magento\Framework\Escaper $escaper */

/** @var Inchoo\Sample03\ViewModel\Custom $viewModel */
$viewModel = $block->getData('view_model');
?>

<h3><?= $escaper->escapeHtml(__('View Model')) ?></h3>

<p><?= $escaper->escapeHtml($viewModel->getStoreName()) ?></p>

<div class="param-list">
    <?php foreach ($viewModel->getRequestParams() as $key => $value) : ?>
        <p><?= $escaper->escapeHtml($key) ?> => <?= $escaper->escapeHtml($value) ?></p>
    <?php endforeach; ?>
</div>
