<?php
/** @var Magento\Framework\View\Element\Template $block */
?>
<div class="field sample-data required">
    <label for="oib" class="label">
        <span><?= __('OIB') ?></span>
    </label>
    <input type="text"
           name="oib"
           title="<?= __('OIB') ?>"
           id="oib"
           class="input-text">

    <label for="mobile_number" class="label">
        <span><?= __('Mobile Number') ?></span>
    </label>
    <input type="number"
           name="mobile_number"
           title="<?= __('Mobile Number') ?>"
           id="mobile_number"
           class="input-text">
</div>
